version: '2'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop
    volumes:
      - $PWD/mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10      
  backend:
    build: backend/.
    environment:
      DB_HOST: db
      SPRING_PROFILE: mysql
    ports: 
      - "9090:8080"
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build: frontend/.
    ports: 
      - "9080:80"
    depends_on: 
      - backend
#
